version: '3.8'

services:
  # 后端API服务
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./api/data:/app/data
    restart: unless-stopped
    networks:
      - delta-network

  # 前端Web服务
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - delta-network

networks:
  delta-network:
    driver: bridge

volumes:
  api-data:
    driver: local
